#!/bin/bash

source systems

colors="
#0066FF
#0BFF00
#FFF100
#FFAC00
#FF0000
"

fonts="
XOVOX-Lazer84
"

mkdir -pv output

for system in ${!system_name[@]} ; do
        systemtext="$(tr '[:lower:]' '[:upper:]' <<< "${system_name[$system]}")"
	echo "echo \"$systemtext\""

	for font in $fonts ; do
		echo "mkdir -pv \"output/$font/\"{big,small}"
		y="10"
		x="0"
		echo -n "convert -size 224x36 xc:transparent -font \"$font\" -pointsize 16 "

		for color in $colors ; do
			echo -n "-gravity north -fill \"$color\" -annotate +$x+$y \"$systemtext\" "
			y=$[ $y - 1 ]
		done
		y=$[ $y - 2 ]
		echo -n "-gravity north -fill \"#FFFFFF\" -stroke \"#000000\" -strokewidth 2 -annotate +$x+$y \"$systemtext\" "
		echo -n "-gravity north -fill \"#FFFFFF\" -stroke none -annotate +$x+$y \"$systemtext\" "

		echo "\"output/$font/small/$system.png\""


		y="40"
		x="0"
		echo -n "convert -size 1000x1000 xc:transparent -font \"$font\" -pointsize 72 "

		for color in $colors ; do
			echo -n "-gravity center -fill \"$color\" -annotate +$x+$y \"$systemtext\" "
			y=$[ $y - 4 ]
		done
		y=$[ $y - 4 ]
		echo -n "-gravity center -fill \"#FFFFFF\" -stroke \"#000000\" -strokewidth 5 -annotate +$x+$y \"$systemtext\" "
		echo -n "-gravity center -fill \"#FFFFFF\" -stroke none -annotate +$x+$y \"$systemtext\" "

		echo "-trim  +repage  -scale \"144x36>\"  \"output/$font/big/$system.png\""
		done


done
