#!/bin/bash

mkdir output
for i in *png ; do
	echo $i


if [ ! -f output/$i ]; then
convert $i +level 10,100% -colorspace gray -depth 2 /tmp/$i
convert -size 2000x2000 xc:transparent \
	-gravity center \
	\( \
		/tmp/$i \
			-colorspace Gray \
			-depth 3 \
			-fill "#0066FF" \
			-tint 100 \
			-fuzz 25% \
			+opaque "#000000" \
			-scale 320x240\> \
	\) \
		-geometry -0+0	\
		-composite \
	\( \
		/tmp/$i \
			-colorspace Gray \
			-depth 3 \
			-fill "#0BFF00" \
			-tint 100 \
			-fuzz 25% \
			+opaque "#000000" \
			-scale 320x240\> \
	\) \
		-geometry -100+0	\
		-composite \
	\( \
		/tmp/$i \
			-colorspace Gray \
			-depth 3 \
			-fill "#FFF100" \
			-tint 100 \
			-fuzz 25% \
			+opaque "#000000" \
			-scale 320x240\> \
	\) \
		-geometry -200+0	\
		-composite \
	\( \
		/tmp/$i \
			-colorspace Gray \
			-depth 3 \
			-fill "#FFAC00" \
			-tint 100 \
			-fuzz 25% \
			+opaque "#000000" \
			-scale 320x240\> \
	\) \
		-geometry -300+0	\
		-composite \
	\( \
		/tmp/$i \
			-colorspace Gray \
			-depth 3 \
			-fill "#FF0000" \
			-tint 100 \
			-fuzz 25% \
			+opaque "#000000" \
			-scale 320x240\> \
	\) \
		-geometry -400+0	\
		-composite \
	-trim +repage \
	-resize 240x280\> \
		output/$i 
fi
done
